export const THAI_MONTHS = [
  "มกราคม",
  "กุมภาพันธ์",
  "มีนาคม",
  "เมษายน",
  "พฤษภาคม",
  "มิถุนายน",
  "กรกฎาคม",
  "สิงหาคม",
  "กันยายน",
  "ตุลาคม",
  "พฤศจิกายน",
  "ธันวาคม",
] as const;

export const CAREER_METRICS_COPY = {
  title: "ตัวชี้วัดสายอาชีพ",
  englishTitle: "Career Metrics",
  sidebarLabel: "พอร์ตผลงาน",
  operationalScale: "ขนาดการดำเนินงาน",
  totalSku: "จำนวน SKU ทั้งหมด",
  totalOrders: "คำสั่งทั้งหมด",
  printingQuantity: "จำนวนงานพิมพ์",
  averageActiveDay: "คำสั่งเฉลี่ยต่อวันที่มีงาน",
  peakDay: "วันที่มีคำสั่งสูงสุด",
  peakHour: "ช่วงเวลาที่มีคำสั่งสูงสุด",
  cancelledOrders: "คำสั่งที่ยกเลิก",
  cancellationRate: "อัตราการยกเลิก",
  qualityAndWaste: "คุณภาพและของเสีย",
  totalPaperWaste: "กระดาษเสียทั้งหมด",
  wasteIncidents: "เหตุการณ์กระดาษเสีย",
  averageWastePerIncident: "เฉลี่ยต่อเหตุการณ์",
  wasteRate: "อัตรากระดาษเสีย",
  wasteCauses: "สาเหตุกระดาษเสีย",
  wasteByPaperType: "ของเสียแยกตามประเภทกระดาษ",
  dailyWasteTrend: "แนวโน้มกระดาษเสียรายวัน",
  historicalPerformance: "แนวโน้มผลงานย้อนหลัง",
  orderedSku: "SKU ที่มีการสั่งงาน",
  monthlyOrders: "ปริมาณคำสั่งรายเดือน",
  monthlyPrintingQuantity: "ปริมาณงานพิมพ์รายเดือน",
  historicalWasteRate: "อัตรากระดาษเสียรายเดือน",
  monthlyPaperWaste: "กระดาษเสียรายเดือน",
  monthlyDetails: "รายละเอียดรายเดือน",
  portfolioSnapshot: "สรุปสำหรับพอร์ตผลงาน",
} as const;
