-- Database Setup for Printer Order Management System
-- Drop old tables if they exist
DROP TABLE IF EXISTS public.enrollments CASCADE;
DROP TABLE IF EXISTS public.courses CASCADE;

-- 1. Users Extension Table (Link to Supabase Auth)
-- We use a custom table to store additional info like roles
CREATE TABLE IF NOT EXISTS public.users (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  name TEXT NOT NULL UNIQUE,
  role TEXT NOT NULL DEFAULT 'user', -- 'admin' or 'user'
  employee_id TEXT,
  job_title TEXT,
  department TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: We assume Supabase Auth will be used to manage passwords instead of raw DB inserts for security.
-- In our app, we will insert into this public.users table after a user signs up.

-- 2. Products Table (fgcode)
CREATE TABLE IF NOT EXISTS public.fgcode (
  id TEXT PRIMARY KEY, -- Product ID (e.g., 'FG-001')
  name TEXT NOT NULL,  -- Product Name
  exp TEXT NOT NULL,   -- Expiration (e.g., '12 months', '2 years')
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert Mock Products
INSERT INTO public.fgcode (id, name, exp)
VALUES
  ('FG-1001', 'ฉลากส้มสายน้ำผึ้ง', '6 months'),
  ('FG-1002', 'สติ๊กเกอร์ติดกล่องพัสดุ', '2 years'),
  ('FG-1003', 'ฉลากขวดน้ำดื่ม', '12 months'),
  ('FG-1004', 'ป้ายราคา', '3 years')
ON CONFLICT (id) DO NOTHING;


-- 3. Orders Table
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date DATE NOT NULL,
  order_time TIME NOT NULL,
  order_datetime TIMESTAMP WITH TIME ZONE NOT NULL,
  lot_number TEXT NOT NULL,
  
  -- Product Details Snapshot
  product_id TEXT REFERENCES public.fgcode(id) ON DELETE SET NULL,
  product_name TEXT NOT NULL,
  product_exp TEXT NOT NULL,
  
  production_date DATE NOT NULL,
  expiry_date DATE NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  notes TEXT,
  
  created_by TEXT NOT NULL, -- Name of the user who created it
  created_by_department TEXT, -- Snapshot of the user's department at the time of order
  
  -- Verification fields (Admin only)
  is_verified BOOLEAN DEFAULT false NOT NULL,
  verified_by TEXT,
  verified_at TIMESTAMP WITH TIME ZONE,
  
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Allow users to manage their own profile info, but admins can manage all
-- For simplicity in this demo without RLS complex rules yet:
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all actions for public users" ON public.users FOR ALL USING (true);

ALTER TABLE public.fgcode ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all actions for public fgcode" ON public.fgcode FOR ALL USING (true);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all actions for public orders" ON public.orders FOR ALL USING (true);

