-- Manager-only registry usage inspection and permanent deletion.
-- Product and Order configs intentionally retain pattern strings, so historical
-- Order snapshots remain independent of registry row lifecycle.

-- Take a compatible row lock whenever a changed Product config selects an
-- enabled registry format. A concurrent delete holds FOR UPDATE on that same
-- registry row, so it either sees the newly saved Product reference or causes
-- this Product change to re-check after the row has been deleted.
CREATE OR REPLACE FUNCTION public.validate_fgcode_printing_config_v1()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
    v_mfg_pattern text;
    v_exp_pattern text;
    v_registry_id uuid;
BEGIN
    PERFORM public.validate_printing_config_v1(NEW.printing_config);

    -- A retired registry entry must not prevent unrelated Product edits. The
    -- unchanged configuration remains grammar-valid, while historical
    -- snapshots are never registry-dependent.
    IF TG_OP = 'UPDATE'
       AND NEW.printing_config IS NOT DISTINCT FROM OLD.printing_config THEN
        RETURN NEW;
    END IF;

    IF NEW.printing_config IS NULL THEN
        RETURN NEW;
    END IF;

    IF jsonb_typeof(NEW.printing_config -> 'mfg_format') <> 'null' THEN
        v_mfg_pattern := NEW.printing_config -> 'mfg_format' ->> 'pattern';

        SELECT f.id
        INTO v_registry_id
        FROM public.printing_date_formats f
        WHERE f.pattern = v_mfg_pattern
          AND f.enabled
        FOR KEY SHARE;

        IF NOT FOUND THEN
            RAISE EXCEPTION
                'printing_config.mfg_format pattern must be an enabled registry format'
                USING ERRCODE = '22023';
        END IF;
    END IF;

    IF jsonb_typeof(NEW.printing_config -> 'exp_format') <> 'null' THEN
        v_exp_pattern := NEW.printing_config -> 'exp_format' ->> 'pattern';

        SELECT f.id
        INTO v_registry_id
        FROM public.printing_date_formats f
        WHERE f.pattern = v_exp_pattern
          AND f.enabled
        FOR KEY SHARE;

        IF NOT FOUND THEN
            RAISE EXCEPTION
                'printing_config.exp_format pattern must be an enabled registry format'
                USING ERRCODE = '22023';
        END IF;
    END IF;

    RETURN NEW;
END;
$function$;


CREATE OR REPLACE FUNCTION public.get_printing_date_format_management_rows()
RETURNS TABLE (
    id uuid,
    pattern text,
    display_label text,
    enabled boolean,
    sort_order integer,
    product_usage_count integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
BEGIN
    IF COALESCE(auth.role(), '') <> 'authenticated'
       OR auth.uid() IS NULL
       OR NOT public.is_user_manager() THEN
        RAISE EXCEPTION 'Manager permission is required';
    END IF;

    RETURN QUERY
    SELECT
        f.id,
        f.pattern,
        f.display_label,
        f.enabled,
        f.sort_order,
        count(p.id)::integer AS product_usage_count
    FROM public.printing_date_formats f
    LEFT JOIN public.fgcode p
        ON (
            p.printing_config -> 'mfg_format' ->> 'pattern' = f.pattern
            OR p.printing_config -> 'exp_format' ->> 'pattern' = f.pattern
        )
    GROUP BY f.id, f.pattern, f.display_label, f.enabled, f.sort_order
    ORDER BY f.sort_order ASC, f.id ASC;
END;
$function$;


CREATE OR REPLACE FUNCTION public.protect_audit_log_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
    v_name text;
    v_employee_id text;
    v_is_internal boolean;
BEGIN
    v_is_internal := COALESCE(current_setting('app.audit_internal', true), 'off') = 'on';
    IF auth.role() = 'authenticated' THEN
        IF NEW.action IN ('CREATE_ORDER','UPDATE','VERIFY','UNVERIFY','RECONCILE','CANCEL_RECONCILE','CANCEL','DELETE_ORDER','RESTORE_FROM_TRASH','PERMANENT_DELETE_ORDER','CREATE_PRODUCT','UPDATE_PRODUCT','RENAME_PRODUCT','DELETE_PRODUCT','DELETE_PRODUCTS','CREATE_USER','UPDATE_USER','UPDATE_PROFILE','DELETE_USER','CREATE_STABILITY_FEED','UPDATE_STABILITY_FEED','DELETE_STABILITY_FEED','STOCK_IN','STOCK_DELETE','CREATE_PRINTING_DATE_FORMAT','UPDATE_PRINTING_DATE_FORMAT','DELETE_PRINTING_DATE_FORMAT')
           AND NOT v_is_internal THEN
            RAISE EXCEPTION 'This audit action must be generated by the database or trusted server';
        END IF;
        SELECT u.name, u.employee_id INTO v_name, v_employee_id FROM public.users u WHERE u.id = auth.uid();
        IF NOT FOUND THEN RAISE EXCEPTION 'User profile not found'; END IF;
        NEW.user_id := auth.uid();
        NEW.user_name := CASE WHEN NULLIF(btrim(v_employee_id), '') IS NOT NULL THEN v_name || ' (' || v_employee_id || ')' ELSE v_name END;
        NEW.created_at := now(); NEW.ip_address := NULL;
    END IF;
    RETURN NEW;
END;
$function$;


CREATE OR REPLACE FUNCTION public.delete_printing_date_format(
    p_id uuid
)
RETURNS TABLE (
    id uuid,
    pattern text,
    display_label text,
    enabled boolean,
    sort_order integer,
    product_usage_count integer
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO ''
AS $function$
DECLARE
    v_format public.printing_date_formats%ROWTYPE;
    v_product_usage_count integer;
    v_previous_audit_flag text;
BEGIN
    IF COALESCE(auth.role(), '') <> 'authenticated'
       OR auth.uid() IS NULL
       OR NOT public.is_user_manager() THEN
        RAISE EXCEPTION 'Manager permission is required';
    END IF;

    IF p_id IS NULL THEN
        RAISE EXCEPTION 'Printing date format ID is required'
            USING ERRCODE = '22023';
    END IF;

    -- This lock serializes deletion with a Product config change that selects
    -- the same enabled pattern (which takes FOR KEY SHARE above).
    SELECT *
    INTO v_format
    FROM public.printing_date_formats f
    WHERE f.id = p_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'Printing date format was not found'
            USING ERRCODE = 'P0002';
    END IF;

    SELECT count(*)::integer
    INTO v_product_usage_count
    FROM public.fgcode p
    WHERE p.printing_config -> 'mfg_format' ->> 'pattern' = v_format.pattern
       OR p.printing_config -> 'exp_format' ->> 'pattern' = v_format.pattern;

    IF v_product_usage_count > 0 THEN
        RAISE EXCEPTION 'Printing date format is still used by % Product(s)', v_product_usage_count
            USING ERRCODE = 'P0001';
    END IF;

    v_previous_audit_flag := current_setting('app.audit_internal', true);
    PERFORM set_config('app.audit_internal', 'on', true);

    INSERT INTO public.audit_logs (action, details)
    VALUES (
        'DELETE_PRINTING_DATE_FORMAT',
        jsonb_build_object(
            'id', v_format.id,
            'code', v_format.code,
            'pattern', v_format.pattern,
            'display_label', v_format.display_label,
            'enabled', v_format.enabled,
            'sort_order', v_format.sort_order,
            'product_usage_count', v_product_usage_count
        )
    );

    DELETE FROM public.printing_date_formats f
    WHERE f.id = v_format.id;

    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );

    RETURN QUERY
    SELECT
        v_format.id,
        v_format.pattern,
        v_format.display_label,
        v_format.enabled,
        v_format.sort_order,
        v_product_usage_count;
END;
$function$;


-- Direct table mutation remains unavailable to application roles. Managers
-- use the narrow authenticated RPCs above and from Phase C instead.
REVOKE DELETE ON TABLE public.printing_date_formats
FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.get_printing_date_format_management_rows()
FROM PUBLIC, anon, service_role;
GRANT EXECUTE ON FUNCTION public.get_printing_date_format_management_rows()
TO authenticated;

REVOKE ALL ON FUNCTION public.delete_printing_date_format(uuid)
FROM PUBLIC, anon, service_role;
GRANT EXECUTE ON FUNCTION public.delete_printing_date_format(uuid)
TO authenticated;

-- validate_fgcode_printing_config_v1 remains an internal trigger function.
REVOKE ALL ON FUNCTION public.validate_fgcode_printing_config_v1()
FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.validate_fgcode_printing_config_v1()
TO postgres, service_role;
