set local check_function_bodies = off;

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on sequences from "service_role";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "anon";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "authenticated";

alter default privileges for role "postgres" in schema "public" revoke all on tables from "service_role";

create extension "pg_cron";

create sequence "public"."stability_feeds_id_seq" as bigint increment by 1 minvalue 1 maxvalue 9223372036854775807 START with 1 cache 1 no cycle;

create table "public"."audit_logs" (
  "id"         uuid                     not null default gen_random_uuid(),
  "user_id"    uuid,
  "action"     text                     not null,
  "details"    jsonb,
  "ip_address" text,
  "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
  "order_id"   bigint,
  "user_name"  character varying(255),
  "summary"    text,
  "changes"    jsonb,
  constraint "audit_logs_pkey" primary key (id)
);

alter table "public"."audit_logs"
  enable row level security;

create table "public"."fgcode" (
  "id"                 text                     not null,
  "name"               text                     not null,
  "exp"                text                     not null,
  "created_at"         timestamp with time zone not null default timezone('utc'::text, now()),
  "default_paper_type" text,
  "qty_per_a3"         integer,
  constraint "fgcode_pkey" primary key (id)
);

alter table "public"."fgcode"
  enable row level security;

create table "public"."orders" (
  "id"                    bigint                   generated by default as identity not null,
  "order_date"            date                     not null,
  "order_time"            time without time zone   not null,
  "order_datetime"        timestamp with time zone not null,
  "lot_number"            text                     not null,
  "product_id"            text,
  "product_name"          text                     not null,
  "product_exp"           text                     not null,
  "production_date"       date                     not null,
  "expiry_date"           date                     not null,
  "quantity"              integer                  not null default 1,
  "notes"                 text,
  "created_by"            text                     not null,
  "is_verified"           boolean                  not null default false,
  "verified_by"           text,
  "verified_at"           timestamp with time zone,
  "created_at"            timestamp with time zone not null default timezone('utc'::text, now()),
  "created_by_department" text,
  "order_type"            text                     default '''พิมฉลาก'''::text,
  "image_url"             text,
  "is_printed"            boolean                  default false,
  "updated_at"            timestamp with time zone,
  "updated_by"            text,
  "edit_summary"          text,
  "is_cancelled"          boolean                  default false,
  "is_no_file"            boolean                  default false,
  "printed_by"            text,
  "printed_by_user_id"    uuid,
  "printed_at"            timestamp with time zone,
  "is_deleted"            boolean                  default false,
  "deleted_at"            timestamp with time zone,
  "deleted_by"            text,
  "previous_product_name" text,
  "no_file_at"            timestamp with time zone,
  "total_paused_ms"       bigint                   default 0,
  "delay_reason"          text,
  "created_by_user_id"    uuid,
  "verified_by_user_id"   uuid,
  "updated_by_user_id"    uuid,
  "paper_type"            text,
  "good_a3"               integer,
  "waste_qty"             integer,
  "waste_qty_remark"      text,
  "waste_a3"              integer,
  "waste_a3_remark"       text,
  "reconciled_by"         text,
  "reconciled_at"         timestamp with time zone,
  "qty_per_a3_used"       numeric,
  constraint "orders_pkey" primary key (id),
  constraint "orders_quantity_check" check ((quantity > 0))
);

alter table "public"."orders"
  enable row level security;

create table "public"."paper_reports" (
  "id"               bigint                   generated by default as identity not null,
  "created_at"       timestamp with time zone not null default timezone('utc'::text, now()),
  "order_id"         bigint,
  "lot_number"       text                     not null,
  "product_id"       text                     not null,
  "department"       text                     not null,
  "paper_type"       text                     not null,
  "target_qty"       integer,
  "target_a3"        integer                  not null,
  "good_a3"          integer                  not null,
  "waste_a3"         integer,
  "waste_qty"        integer,
  "waste_a3_remark"  text,
  "waste_qty_remark" text,
  "report_type"      text                     not null,
  "created_by"       text                     not null,
  "remark"           text,
  "qty_per_a3_used"  numeric,
  constraint "paper_reports_pkey" primary key (id)
);

alter table "public"."paper_reports"
  enable row level security;

create table "public"."paper_transactions" (
  "id"                   uuid                     not null default gen_random_uuid(),
  "date"                 date                     not null default CURRENT_DATE,
  "transaction_type"     text                     not null,
  "paper_type"           text                     not null,
  "qty"                  integer                  not null,
  "description"          text,
  "reference_id"         bigint,
  "created_by"           text,
  "user_id"              uuid,
  "created_at"           timestamp with time zone not null default now(),
  "transaction_category" text,
  constraint "paper_transactions_pkey" primary key (id),
  constraint "paper_transactions_transaction_category_check" check (((transaction_category = ANY (ARRAY['GOOD'::text, 'WASTE'::text])) OR (transaction_category IS NULL))),
  constraint "paper_transactions_transaction_type_check" check ((transaction_type = ANY (ARRAY['IN'::text, 'OUT'::text])))
);

alter table "public"."paper_transactions"
  enable row level security;

create table "public"."stability_feeds" (
  "id"                    bigint                   not null default nextval('public.stability_feeds_id_seq'::regclass),
  "lot_number"            text                     not null,
  "product_id"            text                     not null,
  "product_name"          text                     not null,
  "product_exp"           text,
  "production_date"       date                     not null,
  "expiry_date"           date,
  "feed_type"             text,
  "remark"                text,
  "selected_intervals"    jsonb                    default '[0, 3, 6, 9, 12]'::jsonb,
  "completed_intervals"   jsonb                    default '[]'::jsonb,
  "created_by"            text,
  "created_by_department" text,
  "is_deleted"            boolean                  default false,
  "deleted_by"            text,
  "deleted_at"            timestamp with time zone,
  "created_at"            timestamp with time zone default now(),
  "updated_at"            timestamp with time zone default now(),
  constraint "stability_feeds_pkey" primary key (id)
);

alter table "public"."stability_feeds"
  enable row level security;

create table "public"."users" (
  "id"            uuid                     not null,
  "email"         text                     not null,
  "name"          text                     not null,
  "role"          text                     not null default 'user'::text,
  "created_at"    timestamp with time zone not null default timezone('utc'::text, now()),
  "employee_id"   text,
  "job_title"     text,
  "department"    text,
  "signature_url" text,
  constraint "users_name_key" unique (name),
  constraint "users_pkey" primary key (id)
);

alter table "public"."users"
  enable row level security;

alter sequence "public"."stability_feeds_id_seq" owned by "public"."stability_feeds"."id";

create or replace function public.audit_fgcode_delete()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_count integer;
    v_single_id text;
    v_ids jsonb;
    v_previous_audit_flag text;
BEGIN

    -- rename_fgcode() ลบ ID เก่า แต่ไม่ถือว่า DELETE_PRODUCT
    IF COALESCE(
        current_setting('app.fgcode_rename', true),
        'off'
    ) = 'on' THEN
        RETURN NULL;
    END IF;


    SELECT
        count(*),
        min(id),
        jsonb_agg(id ORDER BY id)
    INTO
        v_count,
        v_single_id,
        v_ids
    FROM deleted_rows;


    IF v_count = 0 THEN
        RETURN NULL;
    END IF;


    v_previous_audit_flag :=
        current_setting('app.audit_internal', true);

    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    IF v_count = 1 THEN

        INSERT INTO public.audit_logs (
            action,
            details
        )
        VALUES (
            'DELETE_PRODUCT',
            jsonb_build_object(
                'id', v_single_id
            )
        );

    ELSE

        INSERT INTO public.audit_logs (
            action,
            details
        )
        VALUES (
            'DELETE_PRODUCTS',
            jsonb_build_object(
                'ids', v_ids,
                'count', v_count
            )
        );

    END IF;


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    RETURN NULL;
END;
$function$;

create or replace function public.audit_fgcode_write()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_previous_audit_flag text;
    v_changes jsonb;
BEGIN

    -- rename_fgcode() จะสร้าง UPDATE_PRODUCT เอง 1 รายการ
    IF COALESCE(
        current_setting('app.fgcode_rename', true),
        'off'
    ) = 'on' THEN
        RETURN NEW;
    END IF;


    -- UPDATE ที่ไม่มีอะไรเปลี่ยนจริง ไม่ต้อง log
    IF TG_OP = 'UPDATE'
       AND NEW.name IS NOT DISTINCT FROM OLD.name
       AND NEW.exp IS NOT DISTINCT FROM OLD.exp
       AND NEW.default_paper_type IS NOT DISTINCT FROM OLD.default_paper_type
       AND NEW.qty_per_a3 IS NOT DISTINCT FROM OLD.qty_per_a3 THEN

        RETURN NEW;
    END IF;


    IF TG_OP = 'UPDATE' THEN

        v_changes := jsonb_strip_nulls(
            jsonb_build_object(

                'name',
                CASE
                    WHEN NEW.name IS DISTINCT FROM OLD.name
                    THEN jsonb_build_object(
                        'old', OLD.name,
                        'new', NEW.name
                    )
                END,

                'exp',
                CASE
                    WHEN NEW.exp IS DISTINCT FROM OLD.exp
                    THEN jsonb_build_object(
                        'old', OLD.exp,
                        'new', NEW.exp
                    )
                END,

                'default_paper_type',
                CASE
                    WHEN NEW.default_paper_type
                         IS DISTINCT FROM OLD.default_paper_type
                    THEN jsonb_build_object(
                        'old', OLD.default_paper_type,
                        'new', NEW.default_paper_type
                    )
                END,

                'qty_per_a3',
                CASE
                    WHEN NEW.qty_per_a3
                         IS DISTINCT FROM OLD.qty_per_a3
                    THEN jsonb_build_object(
                        'old', OLD.qty_per_a3,
                        'new', NEW.qty_per_a3
                    )
                END
            )
        );

    ELSE
        v_changes := NULL;
    END IF;


    v_previous_audit_flag :=
        current_setting('app.audit_internal', true);

    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        details,
        changes
    )
    VALUES (
        CASE
            WHEN TG_OP = 'INSERT'
                THEN 'CREATE_PRODUCT'
            ELSE 'UPDATE_PRODUCT'
        END,

        jsonb_build_object(
            'id', NEW.id,
            'name', NEW.name,
            'exp', NEW.exp,
            'default_paper_type', NEW.default_paper_type,
            'qty_per_a3', NEW.qty_per_a3
        ),

        v_changes
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    RETURN NEW;
END;
$function$;

create or replace function public.audit_orders_changes()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_action text;
    v_summary text;
    v_details jsonb;
    v_previous_audit_flag text;
BEGIN

    -- การ sync ภายในจาก fgcode ไม่สร้าง order audit ปลอม/ซ้ำ
    IF COALESCE(
        current_setting('app.order_internal_write', true),
        'off'
    ) = 'on' THEN

        IF TG_OP = 'DELETE' THEN
            RETURN OLD;
        END IF;

        RETURN NEW;
    END IF;


    -- ========================================================
    -- INSERT = CREATE_ORDER
    -- ========================================================
    IF TG_OP = 'INSERT' THEN

        v_action := 'CREATE_ORDER';
        v_summary := 'สร้างคำสั่งพิมพ์';

        v_details := jsonb_build_object(
            'order_id', NEW.id,
            'product_id', NEW.product_id,
            'product_name', NEW.product_name,
            'lot_number', NEW.lot_number,
            'quantity', NEW.quantity
        );


    -- ========================================================
    -- DELETE จริง = PERMANENT_DELETE_ORDER
    -- ========================================================
    ELSIF TG_OP = 'DELETE' THEN

        v_action := 'PERMANENT_DELETE_ORDER';
        v_summary := 'ลบคำสั่งพิมพ์ถาวร';

        v_details := jsonb_build_object(
            'order_id', OLD.id,
            'product_id', OLD.product_id,
            'product_name', OLD.product_name,
            'lot_number', OLD.lot_number,
            'quantity', OLD.quantity,
            'created_by', OLD.created_by,
            'deleted_by', OLD.deleted_by,
            'deleted_at', OLD.deleted_at
        );


    -- ========================================================
    -- UPDATE
    -- ========================================================
    ELSE

        -- Soft delete
        IF COALESCE(OLD.is_deleted, false) = false
           AND COALESCE(NEW.is_deleted, false) = true THEN

            v_action := 'DELETE_ORDER';
            v_summary := COALESCE(
                NULLIF(NEW.edit_summary, ''),
                'ย้ายคำสั่งพิมพ์ไปถังขยะ'
            );

            v_details := jsonb_build_object(
                'order_id', NEW.id,
                'product_id', NEW.product_id,
                'product_name', NEW.product_name,
                'lot_number', NEW.lot_number,
                'quantity', NEW.quantity,
                'created_by', NEW.created_by,
                'deleted_by', NEW.deleted_by,
                'deleted_at', NEW.deleted_at
            );


        -- Restore
        ELSIF COALESCE(OLD.is_deleted, false) = true
           AND COALESCE(NEW.is_deleted, false) = false THEN

            v_action := 'RESTORE_FROM_TRASH';
            v_summary := COALESCE(
                NULLIF(NEW.edit_summary, ''),
                'กู้คืนคำสั่งพิมพ์จากถังขยะ'
            );

            v_details := jsonb_build_object(
                'order_id', NEW.id,
                'product_id', NEW.product_id,
                'product_name', NEW.product_name,
                'lot_number', NEW.lot_number
            );


        -- Verify
        ELSIF COALESCE(OLD.is_verified, false) = false
           AND COALESCE(NEW.is_verified, false) = true THEN

            v_action := 'VERIFY';
            v_summary := 'ตรวจสอบและยืนยันคำสั่งพิมพ์';
            v_details := NULL;


        -- Unverify
        ELSIF COALESCE(OLD.is_verified, false) = true
           AND COALESCE(NEW.is_verified, false) = false THEN

            v_action := 'UNVERIFY';
            v_summary := 'ยกเลิกการยืนยันคำสั่งพิมพ์';
            v_details := NULL;


        -- Cancel
        ELSIF COALESCE(OLD.is_cancelled, false) = false
           AND COALESCE(NEW.is_cancelled, false) = true THEN

            v_action := 'CANCEL';
            v_summary := COALESCE(
                NULLIF(NEW.edit_summary, ''),
                'ยกเลิกคำสั่งพิมพ์'
            );
            v_details := NULL;


        -- Reconcile
        ELSIF OLD.reconciled_at IS NULL
           AND NEW.reconciled_at IS NOT NULL THEN

            v_action := 'RECONCILE';

            v_summary :=
                'บันทึกผลผลิต: กระดาษดี '
                || COALESCE(NEW.good_a3, 0)::text
                || ' ใบ, เสีย '
                || COALESCE(NEW.waste_a3, 0)::text
                || ' ใบ';

            v_details := NULL;


        -- Cancel reconcile
        ELSIF OLD.reconciled_at IS NOT NULL
           AND NEW.reconciled_at IS NULL THEN

            v_action := 'CANCEL_RECONCILE';
            v_summary := 'ยกเลิกการตัดสต็อคกระดาษ';
            v_details := NULL;


        -- UPDATE ปกติ
        ELSE

            -- ถ้าเปลี่ยนแค่ metadata ที่ระบบ stamp เอง
            -- ไม่ต้องสร้าง audit เพิ่ม
            IF (
                to_jsonb(OLD)
                - ARRAY[
                    'updated_at',
                    'updated_by',
                    'edit_summary'
                ]
            ) = (
                to_jsonb(NEW)
                - ARRAY[
                    'updated_at',
                    'updated_by',
                    'edit_summary'
                ]
            ) THEN
                RETURN NEW;
            END IF;

            v_action := 'UPDATE';

            v_summary := COALESCE(
                NULLIF(NEW.edit_summary, ''),
                'แก้ไขคำสั่งพิมพ์'
            );

            v_details := NULL;

        END IF;

    END IF;


    -- ========================================================
    -- เปิด trusted flag เฉพาะภายใน transaction นี้
    -- ========================================================

    v_previous_audit_flag :=
        current_setting('app.audit_internal', true);

    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        user_id,
        order_id,
        action,
        summary,
        details
    )
    VALUES (
        auth.uid(),
        CASE
            WHEN TG_OP = 'DELETE' THEN OLD.id
            ELSE NEW.id
        END,
        v_action,
        v_summary,
        v_details
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$function$;

create or replace function public.audit_paper_transaction_delete()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_total integer;
    v_row public.paper_transactions%ROWTYPE;
    v_previous_audit_flag text;
BEGIN

    IF auth.role() <> 'authenticated' THEN
        RETURN NULL;
    END IF;


    SELECT count(*)
    INTO v_total
    FROM deleted_rows;


    IF v_total <> 1 THEN
        RETURN NULL;
    END IF;


    SELECT *
    INTO v_row
    FROM deleted_rows
    LIMIT 1;


    -- transaction ที่ผูก source ต้องถูกจัดการจาก workflow ต้นทาง
    IF v_row.reference_id IS NOT NULL THEN
        RETURN NULL;
    END IF;


    v_previous_audit_flag :=
        current_setting(
            'app.audit_internal',
            true
        );


    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        summary,
        details
    )
    VALUES (
        'STOCK_DELETE',
        'ลบรายการ Stock',
        jsonb_build_object(
            'id', v_row.id,
            'paperType', v_row.paper_type,
            'qty', v_row.qty,
            'type', v_row.transaction_type
        )
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    RETURN NULL;
END;
$function$;

create or replace function public.audit_paper_transaction_insert()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_total integer;
    v_row public.paper_transactions%ROWTYPE;
    v_previous_audit_flag text;
BEGIN

    IF auth.role() <> 'authenticated' THEN
        RETURN NULL;
    END IF;


    SELECT count(*)
    INTO v_total
    FROM inserted_rows;


    -- STOCK page insert ทีละ 1 รายการ
    IF v_total <> 1 THEN
        RETURN NULL;
    END IF;


    SELECT *
    INTO v_row
    FROM inserted_rows
    LIMIT 1;


    -- STOCK_IN = manual IN ที่ไม่ได้ผูก Order/Report
    IF v_row.transaction_type <> 'IN'
       OR v_row.reference_id IS NOT NULL
       OR v_row.transaction_category IS NOT NULL THEN

        RETURN NULL;

    END IF;


    -- weekly reset carry-forward ไม่ถือเป็น manual STOCK_IN
    IF v_row.description =
       'ยกยอดสต็อคคงเหลือจากการรีเซ็ตประจำสัปดาห์'
    THEN
        RETURN NULL;
    END IF;


    v_previous_audit_flag :=
        current_setting(
            'app.audit_internal',
            true
        );


    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        summary,
        details
    )
    VALUES (
        'STOCK_IN',
        'รับกระดาษเข้าส stock',
        jsonb_build_object(
            'id', v_row.id,
            'paperType', v_row.paper_type,
            'qty', v_row.qty,
            'description', v_row.description
        )
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    RETURN NULL;
END;
$function$;

create or replace function public.audit_stability_feed_changes()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_action text;
    v_summary text;
    v_details jsonb;
    v_changes jsonb := '{}'::jsonb;
    v_previous_audit_flag text;
BEGIN

    -- ========================================================
    -- INSERT
    -- ========================================================

    IF TG_OP = 'INSERT' THEN

        v_action := 'CREATE_STABILITY_FEED';
        v_summary := 'สร้าง Stability Feed';

        v_details := jsonb_build_object(
            'id', NEW.id,
            'product_id', NEW.product_id,
            'product_name', NEW.product_name,
            'lot_number', NEW.lot_number
        );


    -- ========================================================
    -- UPDATE
    -- ========================================================

    ELSE

        -- เปลี่ยนแค่ updated_at ไม่ต้อง audit
        IF (
            to_jsonb(OLD)
            - ARRAY['updated_at']
        ) = (
            to_jsonb(NEW)
            - ARRAY['updated_at']
        ) THEN
            RETURN NEW;
        END IF;


        -- Soft delete
        IF COALESCE(OLD.is_deleted, false) = false
           AND COALESCE(NEW.is_deleted, false) = true
        THEN

            v_action := 'DELETE_STABILITY_FEED';
            v_summary := 'ลบ Stability Feed';

        ELSE

            v_action := 'UPDATE_STABILITY_FEED';
            v_summary := 'แก้ไข Stability Feed';

        END IF;


        -- ====================================================
        -- changes
        -- ====================================================

        IF NEW.lot_number IS DISTINCT FROM OLD.lot_number THEN
            v_changes := v_changes || jsonb_build_object(
                'lot_number',
                jsonb_build_object(
                    'old', OLD.lot_number,
                    'new', NEW.lot_number
                )
            );
        END IF;


        IF NEW.product_id IS DISTINCT FROM OLD.product_id THEN
            v_changes := v_changes || jsonb_build_object(
                'product_id',
                jsonb_build_object(
                    'old', OLD.product_id,
                    'new', NEW.product_id
                )
            );
        END IF;


        IF NEW.product_name IS DISTINCT FROM OLD.product_name THEN
            v_changes := v_changes || jsonb_build_object(
                'product_name',
                jsonb_build_object(
                    'old', OLD.product_name,
                    'new', NEW.product_name
                )
            );
        END IF;


        IF NEW.product_exp IS DISTINCT FROM OLD.product_exp THEN
            v_changes := v_changes || jsonb_build_object(
                'product_exp',
                jsonb_build_object(
                    'old', OLD.product_exp,
                    'new', NEW.product_exp
                )
            );
        END IF;


        IF NEW.production_date
           IS DISTINCT FROM OLD.production_date THEN

            v_changes := v_changes || jsonb_build_object(
                'production_date',
                jsonb_build_object(
                    'old', OLD.production_date,
                    'new', NEW.production_date
                )
            );
        END IF;


        IF NEW.expiry_date
           IS DISTINCT FROM OLD.expiry_date THEN

            v_changes := v_changes || jsonb_build_object(
                'expiry_date',
                jsonb_build_object(
                    'old', OLD.expiry_date,
                    'new', NEW.expiry_date
                )
            );
        END IF;


        IF NEW.feed_type IS DISTINCT FROM OLD.feed_type THEN
            v_changes := v_changes || jsonb_build_object(
                'feed_type',
                jsonb_build_object(
                    'old', OLD.feed_type,
                    'new', NEW.feed_type
                )
            );
        END IF;


        IF NEW.remark IS DISTINCT FROM OLD.remark THEN
            v_changes := v_changes || jsonb_build_object(
                'remark',
                jsonb_build_object(
                    'old', OLD.remark,
                    'new', NEW.remark
                )
            );
        END IF;


        IF NEW.selected_intervals
           IS DISTINCT FROM OLD.selected_intervals THEN

            v_changes := v_changes || jsonb_build_object(
                'selected_intervals',
                jsonb_build_object(
                    'old', OLD.selected_intervals,
                    'new', NEW.selected_intervals
                )
            );
        END IF;


        IF NEW.completed_intervals
           IS DISTINCT FROM OLD.completed_intervals THEN

            v_changes := v_changes || jsonb_build_object(
                'completed_intervals',
                jsonb_build_object(
                    'old', OLD.completed_intervals,
                    'new', NEW.completed_intervals
                )
            );
        END IF;


        IF NEW.is_deleted
           IS DISTINCT FROM OLD.is_deleted THEN

            v_changes := v_changes || jsonb_build_object(
                'is_deleted',
                jsonb_build_object(
                    'old', OLD.is_deleted,
                    'new', NEW.is_deleted
                )
            );
        END IF;


        v_details := jsonb_build_object(
            'id', NEW.id,
            'product_id', NEW.product_id,
            'product_name', NEW.product_name,
            'lot_number', NEW.lot_number,
            'deleted_by', NEW.deleted_by,
            'deleted_at', NEW.deleted_at
        );

    END IF;


    -- ========================================================
    -- Trusted insert into audit_logs
    -- ========================================================

    v_previous_audit_flag :=
        current_setting(
            'app.audit_internal',
            true
        );


    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        summary,
        details,
        changes
    )
    VALUES (
        v_action,
        v_summary,
        v_details,
        CASE
            WHEN TG_OP = 'UPDATE'
            THEN v_changes
            ELSE NULL
        END
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    RETURN NEW;
END;
$function$;

create or replace function public.audit_users_write()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_action text;
    v_summary text;
    v_details jsonb;
    v_changes jsonb := '{}'::jsonb;
    v_previous_audit_flag text;
BEGIN

    -- service_role / internal writes ให้ trusted API เป็นคน audit
    IF auth.role() <> 'authenticated' THEN
        RETURN NEW;
    END IF;


    -- ========================================================
    -- INSERT
    -- ========================================================

    IF TG_OP = 'INSERT' THEN

        v_action := 'CREATE_USER';
        v_summary := 'สร้างผู้ใช้';

        v_details := jsonb_build_object(
            'id', NEW.id,
            'email', NEW.email,
            'name', NEW.name,
            'role', NEW.role,
            'employee_id', NEW.employee_id,
            'job_title', NEW.job_title,
            'department', NEW.department
        );


    -- ========================================================
    -- UPDATE
    -- ========================================================

    ELSE

        IF NEW.email IS DISTINCT FROM OLD.email THEN
            v_changes := v_changes || jsonb_build_object(
                'email',
                jsonb_build_object(
                    'old', OLD.email,
                    'new', NEW.email
                )
            );
        END IF;


        IF NEW.name IS DISTINCT FROM OLD.name THEN
            v_changes := v_changes || jsonb_build_object(
                'name',
                jsonb_build_object(
                    'old', OLD.name,
                    'new', NEW.name
                )
            );
        END IF;


        IF NEW.role IS DISTINCT FROM OLD.role THEN
            v_changes := v_changes || jsonb_build_object(
                'role',
                jsonb_build_object(
                    'old', OLD.role,
                    'new', NEW.role
                )
            );
        END IF;


        IF NEW.employee_id IS DISTINCT FROM OLD.employee_id THEN
            v_changes := v_changes || jsonb_build_object(
                'employee_id',
                jsonb_build_object(
                    'old', OLD.employee_id,
                    'new', NEW.employee_id
                )
            );
        END IF;


        IF NEW.job_title IS DISTINCT FROM OLD.job_title THEN
            v_changes := v_changes || jsonb_build_object(
                'job_title',
                jsonb_build_object(
                    'old', OLD.job_title,
                    'new', NEW.job_title
                )
            );
        END IF;


        IF NEW.department IS DISTINCT FROM OLD.department THEN
            v_changes := v_changes || jsonb_build_object(
                'department',
                jsonb_build_object(
                    'old', OLD.department,
                    'new', NEW.department
                )
            );
        END IF;


        IF NEW.signature_url IS DISTINCT FROM OLD.signature_url THEN
            v_changes := v_changes || jsonb_build_object(
                'signature_url',
                jsonb_build_object(
                    'old',
                    CASE
                        WHEN OLD.signature_url IS NULL
                        THEN NULL
                        ELSE '[signature]'
                    END,

                    'new',
                    CASE
                        WHEN NEW.signature_url IS NULL
                        THEN NULL
                        ELSE '[signature]'
                    END
                )
            );
        END IF;


        -- ไม่มี field สำคัญเปลี่ยนจริง
        IF v_changes = '{}'::jsonb THEN
            RETURN NEW;
        END IF;


        -- Self-profile update
        IF NEW.id = auth.uid()
           AND NEW.email IS NOT DISTINCT FROM OLD.email
           AND NEW.role IS NOT DISTINCT FROM OLD.role
           AND NEW.signature_url IS NOT DISTINCT FROM OLD.signature_url
        THEN
            v_action := 'UPDATE_PROFILE';
            v_summary := 'แก้ไขโปรไฟล์';

        ELSE
            v_action := 'UPDATE_USER';
            v_summary := 'แก้ไขข้อมูลผู้ใช้';
        END IF;


        v_details := jsonb_build_object(
            'id', NEW.id,
            'email', NEW.email,
            'name', NEW.name,
            'role', NEW.role
        );

    END IF;


    -- ========================================================
    -- TRUSTED AUDIT INSERT
    -- ========================================================

    v_previous_audit_flag :=
        current_setting(
            'app.audit_internal',
            true
        );


    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        summary,
        details,
        changes
    )
    VALUES (
        v_action,
        v_summary,
        v_details,
        CASE
            WHEN TG_OP = 'UPDATE'
            THEN v_changes
            ELSE NULL
        END
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    RETURN NEW;
END;
$function$;

create or replace function public.block_orders_no_file_non_manager()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
BEGIN
    -- ข้ามงานภายในระบบ
    IF current_setting('app.order_internal_write', true) = 'on' THEN
        RETURN NEW;
    END IF;

    -- จำกัดเฉพาะ request จาก authenticated user
    IF auth.role() = 'authenticated'
       AND NOT public.is_user_manager()
       AND NEW.is_no_file IS DISTINCT FROM OLD.is_no_file
    THEN
        RAISE EXCEPTION 'Only moderator or assistant moderator can change is_no_file';
    END IF;

    RETURN NEW;
END;
$function$;

create or replace function public.can_access_stability_feeds()
  returns boolean
  language sql
  stable
  security definer
  set search_path to ''
  AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.id = auth.uid()
          AND (
                u.role IN (
                    'moderator',
                    'assistant_moderator',
                    'operator'
                )
                OR (
                    u.role = 'user'
                    AND u.department = 'QA ประกันคุณภาพ'
                )
          )
    );
$function$;

create or replace function public.is_user_manager()
  returns boolean
  language sql
  stable
  security definer
  set search_path to ''
  AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.id = auth.uid()
          AND u.role IN (
              'moderator',
              'assistant_moderator'
          )
    );
$function$;

create or replace function public.is_user_moderator()
  returns boolean
  language sql
  stable
  security definer
  set search_path to ''
  AS $function$
    SELECT EXISTS (
        SELECT 1
        FROM public.users u
        WHERE u.id = auth.uid()
          AND u.role = 'moderator'
    );
$function$;

create or replace function public.protect_audit_log_insert()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_name text;
    v_employee_id text;
    v_is_internal boolean;
BEGIN

    v_is_internal :=
        COALESCE(
            current_setting(
                'app.audit_internal',
                true
            ),
            'off'
        ) = 'on';


    IF auth.role() = 'authenticated' THEN

        IF NEW.action IN (

            -- orders
            'CREATE_ORDER',
            'UPDATE',
            'VERIFY',
            'UNVERIFY',
            'RECONCILE',
            'CANCEL_RECONCILE',
            'CANCEL',
            'DELETE_ORDER',
            'RESTORE_FROM_TRASH',
            'PERMANENT_DELETE_ORDER',

            -- products
            'CREATE_PRODUCT',
            'UPDATE_PRODUCT',
            'DELETE_PRODUCT',
            'DELETE_PRODUCTS',

            -- users
            'CREATE_USER',
            'UPDATE_USER',
            'UPDATE_PROFILE',
            'DELETE_USER',

            -- stability
            'CREATE_STABILITY_FEED',
            'UPDATE_STABILITY_FEED',
            'DELETE_STABILITY_FEED',

            -- stock
            'STOCK_IN',
            'STOCK_DELETE'

        )
        AND NOT v_is_internal THEN

            RAISE EXCEPTION
                'This audit action must be generated by the database or trusted server';

        END IF;


        SELECT
            u.name,
            u.employee_id
        INTO
            v_name,
            v_employee_id
        FROM public.users u
        WHERE u.id = auth.uid();


        IF NOT FOUND THEN
            RAISE EXCEPTION
                'User profile not found';
        END IF;


        NEW.user_id := auth.uid();

        NEW.user_name :=
            CASE
                WHEN NULLIF(
                    btrim(v_employee_id),
                    ''
                ) IS NOT NULL
                THEN
                    v_name
                    || ' ('
                    || v_employee_id
                    || ')'
                ELSE
                    v_name
            END;


        NEW.created_at := now();
        NEW.ip_address := NULL;

    END IF;


    RETURN NEW;
END;
$function$;

create or replace function public.protect_audit_logs_immutable()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
BEGIN

    IF auth.role() IN ('authenticated', 'anon') THEN
        RAISE EXCEPTION 'Audit logs are append-only';
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$function$;

create or replace function public.protect_fgcode_fields()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_is_manager boolean := false;
BEGIN

    IF auth.role() = 'authenticated' THEN

        v_is_manager := public.is_user_manager();


        -- ====================================================
        -- INSERT
        -- ====================================================

        IF TG_OP = 'INSERT' THEN

            -- user ทั่วไปเพิ่มสินค้าได้
            -- แต่ห้ามกำหนด field สำหรับ manager
            IF NOT v_is_manager THEN

                IF NEW.default_paper_type IS NOT NULL THEN
                    RAISE EXCEPTION
                        'Only moderator or assistant_moderator can set default_paper_type';
                END IF;

                IF NEW.qty_per_a3 IS NOT NULL THEN
                    RAISE EXCEPTION
                        'Only moderator or assistant_moderator can set qty_per_a3';
                END IF;

            END IF;

            RETURN NEW;

        END IF;


        -- ====================================================
        -- UPDATE
        -- ====================================================

        IF TG_OP = 'UPDATE' THEN

            -- id ห้ามเปลี่ยนผ่าน UPDATE ปกติ
            -- ต้องใช้ rename_fgcode()
            IF NEW.id IS DISTINCT FROM OLD.id THEN
                RAISE EXCEPTION
                    'Product ID must be changed through rename_fgcode()';
            END IF;


            -- created_at ห้ามเปลี่ยน
            IF NEW.created_at IS DISTINCT FROM OLD.created_at THEN
                RAISE EXCEPTION
                    'created_at cannot be modified';
            END IF;


            -- user ที่ไม่ใช่ moderator / assistant
            IF NOT v_is_manager THEN

                IF NEW.default_paper_type
                   IS DISTINCT FROM OLD.default_paper_type THEN

                    RAISE EXCEPTION
                        'Only moderator or assistant_moderator can change default_paper_type';

                END IF;


                IF NEW.qty_per_a3
                   IS DISTINCT FROM OLD.qty_per_a3 THEN

                    RAISE EXCEPTION
                        'Only moderator or assistant_moderator can change qty_per_a3';

                END IF;

            END IF;

            RETURN NEW;

        END IF;

    END IF;


    RETURN NEW;

END;
$function$;

create or replace function public.protect_orders_update()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_is_manager boolean := false;
    v_name text;
    v_employee_id text;
    v_editor text;
    v_cancelling boolean := false;
    v_restoring boolean := false;
BEGIN

    -- DB internal sync จาก fgcode
    IF current_setting(
        'app.order_internal_write',
        true
    ) = 'on' THEN
        RETURN NEW;
    END IF;


    IF auth.role() <> 'authenticated' THEN
        RETURN NEW;
    END IF;


    v_is_manager := public.is_user_manager();


    SELECT
        u.name,
        u.employee_id
    INTO
        v_name,
        v_employee_id
    FROM public.users u
    WHERE u.id = auth.uid();


    IF NOT FOUND THEN
        RAISE EXCEPTION 'User profile not found';
    END IF;


    v_editor :=
        CASE
            WHEN v_employee_id IS NOT NULL
                 AND btrim(v_employee_id) <> ''
            THEN v_name || ' (' || v_employee_id || ')'
            ELSE v_name
        END;


    -- =====================================================
    -- ห้ามเปลี่ยน identity / creator
    -- =====================================================

    IF NEW.id IS DISTINCT FROM OLD.id THEN
        RAISE EXCEPTION 'Order ID cannot be changed';
    END IF;

    IF NEW.created_by_user_id
       IS DISTINCT FROM OLD.created_by_user_id THEN
        RAISE EXCEPTION 'Order creator cannot be changed';
    END IF;

    IF NEW.created_by
       IS DISTINCT FROM OLD.created_by THEN
        RAISE EXCEPTION 'Order creator cannot be changed';
    END IF;

    IF NEW.created_by_department
       IS DISTINCT FROM OLD.created_by_department THEN
        RAISE EXCEPTION
            'Order creator department cannot be changed';
    END IF;

    IF NEW.created_at
       IS DISTINCT FROM OLD.created_at THEN
        RAISE EXCEPTION 'created_at cannot be changed';
    END IF;


    v_cancelling :=
        COALESCE(NEW.is_cancelled, false)
        AND NOT COALESCE(OLD.is_cancelled, false);

    v_restoring :=
        NOT COALESCE(NEW.is_cancelled, false)
        AND COALESCE(OLD.is_cancelled, false);


    -- =====================================================
    -- USER / OPERATOR
    -- แก้ได้เฉพาะ order ตัวเอง
    -- และเฉพาะ field ที่หน้า Dashboard อนุญาต
    -- =====================================================

    IF NOT v_is_manager THEN

        IF OLD.created_by_user_id IS DISTINCT FROM auth.uid() THEN
            RAISE EXCEPTION
                'You can only update your own order';
        END IF;

        IF OLD.is_verified = true THEN
            RAISE EXCEPTION
                'Verified order cannot be edited';
        END IF;

        IF COALESCE(OLD.is_cancelled, false) = true THEN
            RAISE EXCEPTION
                'Cancelled order cannot be edited';
        END IF;

        IF COALESCE(OLD.is_deleted, false) = true THEN
            RAISE EXCEPTION
                'Deleted order cannot be edited';
        END IF;


        -- เหลือเฉพาะ field ที่ user แก้ได้
        IF (
            to_jsonb(NEW)
            - ARRAY[
                'order_type',
                'lot_number',
                'quantity',
                'production_date',
                'expiry_date',
                'notes',
                'is_cancelled',
                'is_printed',
                'updated_at',
                'updated_by',
                'edit_summary'
            ]
        )
        IS DISTINCT FROM
        (
            to_jsonb(OLD)
            - ARRAY[
                'order_type',
                'lot_number',
                'quantity',
                'production_date',
                'expiry_date',
                'notes',
                'is_cancelled',
                'is_printed',
                'updated_at',
                'updated_by',
                'edit_summary'
            ]
        ) THEN
            RAISE EXCEPTION
                'You are not allowed to change protected order fields';
        END IF;


        -- user ยกเลิกได้ แต่กู้คืนเองไม่ได้
        IF NEW.is_cancelled IS DISTINCT FROM OLD.is_cancelled
           AND NOT v_cancelling THEN
            RAISE EXCEPTION
                'Only Moderator can restore an order';
        END IF;


        -- user เปลี่ยนสถานะ print เองไม่ได้
        -- ยกเว้นตอน cancel ระบบต้อง reset print
        IF NEW.is_printed IS DISTINCT FROM OLD.is_printed
           AND NOT v_cancelling THEN
            RAISE EXCEPTION
                'Print status can only be changed by Moderator';
        END IF;


        -- audit identity ให้ DB กำหนด
        NEW.updated_at := now();
        NEW.updated_by := v_editor;
        NEW.updated_by_user_id := auth.uid();

    END IF;


    -- =====================================================
    -- CANCEL
    -- =====================================================

    IF v_cancelling THEN

        IF OLD.is_verified = true THEN
            RAISE EXCEPTION
                'Verified order must be unverified before cancellation';
        END IF;

        -- cancel ต้องคืน status อื่น
        NEW.is_verified := false;
        NEW.verified_by := NULL;
        NEW.verified_by_user_id := NULL;
        NEW.verified_at := NULL;

        NEW.is_printed := false;
        NEW.printed_by := NULL;
        NEW.printed_by_user_id := NULL;
        NEW.printed_at := NULL;

        NEW.is_no_file := false;
        NEW.no_file_at := NULL;

    END IF;


    -- =====================================================
    -- RESTORE
    -- เฉพาะ manager
    -- =====================================================

    IF v_restoring THEN

        IF NOT v_is_manager THEN
            RAISE EXCEPTION
                'Only Moderator can restore orders';
        END IF;

        NEW.is_verified := false;
        NEW.verified_by := NULL;
        NEW.verified_by_user_id := NULL;
        NEW.verified_at := NULL;

        NEW.is_printed := false;
        NEW.printed_by := NULL;
        NEW.printed_by_user_id := NULL;
        NEW.printed_at := NULL;

        NEW.is_no_file := false;
        NEW.no_file_at := NULL;

    END IF;


    -- =====================================================
    -- VERIFY / UNVERIFY
    -- =====================================================

    IF NEW.is_verified IS DISTINCT FROM OLD.is_verified THEN

        IF NOT v_is_manager THEN
            RAISE EXCEPTION
                'Only Moderator can verify orders';
        END IF;


        IF NEW.is_verified = true THEN

            IF COALESCE(OLD.is_cancelled, false) = true THEN
                RAISE EXCEPTION
                    'Cancelled order cannot be verified';
            END IF;

            NEW.verified_by := v_editor;
            NEW.verified_by_user_id := auth.uid();
            NEW.verified_at := now();

        ELSE

            IF OLD.verified_by_user_id
               IS DISTINCT FROM auth.uid() THEN
                RAISE EXCEPTION
                    'Only the original verifier can unverify this order';
            END IF;

            NEW.verified_by := NULL;
            NEW.verified_by_user_id := NULL;
            NEW.verified_at := NULL;

        END IF;

    ELSE

        -- ห้ามแก้ metadata verifier โดยไม่เปลี่ยนสถานะ
        IF NEW.verified_by
              IS DISTINCT FROM OLD.verified_by
           OR NEW.verified_by_user_id
              IS DISTINCT FROM OLD.verified_by_user_id
           OR NEW.verified_at
              IS DISTINCT FROM OLD.verified_at THEN

            RAISE EXCEPTION
                'Verification metadata cannot be changed directly';

        END IF;

    END IF;


    -- =====================================================
    -- PRINT / UNPRINT
    -- =====================================================

    IF NEW.is_printed IS DISTINCT FROM OLD.is_printed THEN

        IF v_cancelling THEN

            NEW.is_printed := false;
            NEW.printed_by := NULL;
            NEW.printed_by_user_id := NULL;
            NEW.printed_at := NULL;

        ELSE

            IF NOT v_is_manager THEN
                RAISE EXCEPTION
                    'Only Moderator can change print status';
            END IF;


            IF COALESCE(NEW.is_printed, false) = true THEN

                IF OLD.is_verified = true
                   OR COALESCE(OLD.is_cancelled, false) = true THEN
                    RAISE EXCEPTION
                        'This order cannot be marked as printed';
                END IF;

                NEW.printed_by := v_editor;
                NEW.printed_by_user_id := auth.uid();
                NEW.printed_at := now();

            ELSE

                IF OLD.printed_by_user_id
                   IS DISTINCT FROM auth.uid() THEN
                    RAISE EXCEPTION
                        'Only the original printer can undo printing';
                END IF;

                NEW.printed_by := NULL;
                NEW.printed_by_user_id := NULL;
                NEW.printed_at := NULL;

            END IF;

        END IF;

    ELSE

        IF NEW.printed_by
              IS DISTINCT FROM OLD.printed_by
           OR NEW.printed_by_user_id
              IS DISTINCT FROM OLD.printed_by_user_id
           OR NEW.printed_at
              IS DISTINCT FROM OLD.printed_at THEN

            RAISE EXCEPTION
                'Print metadata cannot be changed directly';

        END IF;

    END IF;


    -- =====================================================
    -- NO FILE
    -- =====================================================

    IF NEW.is_no_file IS DISTINCT FROM OLD.is_no_file THEN

        IF NOT v_is_manager AND NOT v_cancelling THEN
            RAISE EXCEPTION
                'Only Moderator can change no-file status';
        END IF;

        IF COALESCE(NEW.is_no_file, false) = true THEN
            NEW.no_file_at := now();
        ELSE
            NEW.no_file_at := NULL;
        END IF;

    ELSE

        IF NEW.no_file_at
           IS DISTINCT FROM OLD.no_file_at THEN
            RAISE EXCEPTION
                'no_file_at cannot be changed directly';
        END IF;

    END IF;


    -- =====================================================
    -- SOFT DELETE / RESTORE FROM TRASH
    -- =====================================================

    IF NEW.is_deleted IS DISTINCT FROM OLD.is_deleted THEN

        IF NOT v_is_manager THEN
            RAISE EXCEPTION
                'Only Moderator can delete orders';
        END IF;

        IF COALESCE(NEW.is_deleted, false) = true THEN

            NEW.deleted_at := now();
            NEW.deleted_by := v_editor;

        ELSE

            NEW.deleted_at := NULL;
            NEW.deleted_by := NULL;

        END IF;

    ELSE

        IF NEW.deleted_at
              IS DISTINCT FROM OLD.deleted_at
           OR NEW.deleted_by
              IS DISTINCT FROM OLD.deleted_by THEN

            RAISE EXCEPTION
                'Delete metadata cannot be changed directly';

        END IF;

    END IF;


    RETURN NEW;
END;
$function$;

create or replace function public.protect_paper_transaction_fields()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_name text;
BEGIN

    IF auth.role() <> 'authenticated' THEN
        RETURN NEW;
    END IF;


    SELECT u.name
    INTO v_name
    FROM public.users u
    WHERE u.id = auth.uid();


    IF NOT FOUND THEN
        RAISE EXCEPTION 'User profile not found';
    END IF;


    IF NEW.qty IS NULL OR NEW.qty <= 0 THEN
        RAISE EXCEPTION
            'Paper transaction quantity must be greater than 0';
    END IF;


    -- IN ไม่ควรมี GOOD/WASTE category
    IF NEW.transaction_type = 'IN'
       AND NEW.transaction_category IS NOT NULL THEN

        RAISE EXCEPTION
            'IN transaction cannot have transaction_category';

    END IF;


    -- ========================================================
    -- INSERT
    -- ========================================================

    IF TG_OP = 'INSERT' THEN

        NEW.user_id := auth.uid();
        NEW.created_by := v_name;

        NEW.created_at := now();

        NEW.date :=
            (now() AT TIME ZONE 'Asia/Bangkok')::date;

        RETURN NEW;

    END IF;


    -- ========================================================
    -- UPDATE
    -- identity / source metadata ห้ามเปลี่ยน
    -- Dashboard ยังแก้ paper_type / qty / category / description ได้
    -- ========================================================

    IF NEW.id IS DISTINCT FROM OLD.id THEN
        RAISE EXCEPTION
            'Paper transaction ID cannot be changed';
    END IF;


    IF NEW.transaction_type
       IS DISTINCT FROM OLD.transaction_type THEN

        RAISE EXCEPTION
            'transaction_type cannot be changed';

    END IF;


    IF NEW.reference_id
       IS DISTINCT FROM OLD.reference_id THEN

        RAISE EXCEPTION
            'reference_id cannot be changed';

    END IF;


    IF NEW.user_id
       IS DISTINCT FROM OLD.user_id THEN

        RAISE EXCEPTION
            'user_id cannot be changed';

    END IF;


    IF NEW.created_by
       IS DISTINCT FROM OLD.created_by THEN

        RAISE EXCEPTION
            'created_by cannot be changed';

    END IF;


    IF NEW.created_at
       IS DISTINCT FROM OLD.created_at THEN

        RAISE EXCEPTION
            'created_at cannot be changed';

    END IF;


    IF NEW.date
       IS DISTINCT FROM OLD.date THEN

        RAISE EXCEPTION
            'transaction date cannot be changed';

    END IF;


    RETURN NEW;
END;
$function$;

create or replace function public.protect_stability_feed_fields()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_name text;
    v_department text;
BEGIN

    IF auth.role() <> 'authenticated' THEN
        RETURN NEW;
    END IF;


    SELECT
        u.name,
        u.department
    INTO
        v_name,
        v_department
    FROM public.users u
    WHERE u.id = auth.uid();


    IF NOT FOUND THEN
        RAISE EXCEPTION 'User profile not found';
    END IF;


    -- ========================================================
    -- INSERT
    -- ========================================================

    IF TG_OP = 'INSERT' THEN

        NEW.created_by := v_name;

        NEW.created_by_department :=
            COALESCE(
                NULLIF(btrim(v_department), ''),
                'ไม่ระบุหน่วยงาน'
            );

        NEW.is_deleted := false;
        NEW.deleted_by := NULL;
        NEW.deleted_at := NULL;

        NEW.created_at := now();
        NEW.updated_at := now();

        RETURN NEW;
    END IF;


    -- ========================================================
    -- UPDATE
    -- ========================================================

    -- รายการที่ถูกลบแล้วห้ามแก้หรือ restore จาก browser
    IF COALESCE(OLD.is_deleted, false) = true THEN
        RAISE EXCEPTION
            'Deleted stability feed cannot be modified';
    END IF;


    -- identity / creator ให้คงค่าจาก DB
    NEW.id := OLD.id;
    NEW.created_at := OLD.created_at;
    NEW.created_by := OLD.created_by;
    NEW.created_by_department :=
        OLD.created_by_department;


    -- Soft delete
    IF COALESCE(NEW.is_deleted, false) = true THEN

        NEW.is_deleted := true;
        NEW.deleted_by := v_name;
        NEW.deleted_at := now();

    ELSE

        NEW.is_deleted := false;
        NEW.deleted_by := NULL;
        NEW.deleted_at := NULL;

    END IF;


    NEW.updated_at := now();

    RETURN NEW;
END;
$function$;

create or replace function public.protect_user_signature_change()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
BEGIN

    IF NEW.signature_url
       IS DISTINCT FROM OLD.signature_url
    THEN

        IF COALESCE(auth.role(), '') = 'authenticated'
           AND NOT public.is_user_moderator()
        THEN
            RAISE EXCEPTION
                'Only Moderator can modify user signatures';
        END IF;

    END IF;

    RETURN NEW;
END;
$function$;

create or replace function public.protect_users_security_fields()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_is_manager boolean := false;
BEGIN

    IF auth.role() = 'authenticated' THEN

        v_is_manager := public.is_user_manager();

        -- =========================================
        -- INSERT
        -- =========================================
        IF TG_OP = 'INSERT' THEN

            IF NOT v_is_manager THEN

                -- สร้างได้เฉพาะ profile ตัวเอง
                IF NEW.id IS DISTINCT FROM auth.uid() THEN
                    RAISE EXCEPTION
                        'You can only create your own profile';
                END IF;

                -- user ใหม่ห้ามกำหนด role เอง
                NEW.role := 'user';

                -- department ต้องให้ moderator/assistant กำหนด
                NEW.department := NULL;

            END IF;

            RETURN NEW;

        END IF;


        -- =========================================
        -- UPDATE
        -- =========================================
        IF TG_OP = 'UPDATE' THEN

            -- id ห้ามเปลี่ยนทุก app role
            IF NEW.id IS DISTINCT FROM OLD.id THEN
                RAISE EXCEPTION
                    'User ID cannot be changed';
            END IF;

            IF NOT v_is_manager THEN

                -- user แก้ได้เฉพาะ profile ตัวเอง
                IF OLD.id IS DISTINCT FROM auth.uid() THEN
                    RAISE EXCEPTION
                        'You can only update your own profile';
                END IF;

                -- role ห้ามเปลี่ยนเอง
                IF NEW.role IS DISTINCT FROM OLD.role THEN
                    RAISE EXCEPTION
                        'Role can only be changed by moderator';
                END IF;

                -- department ห้ามเปลี่ยนเอง
                IF NEW.department IS DISTINCT FROM OLD.department THEN
                    RAISE EXCEPTION
                        'Department can only be changed by moderator';
                END IF;

            END IF;

            RETURN NEW;

        END IF;

    END IF;

    RETURN NEW;

END;
$function$;

create or replace function public.record_login_audit()
  returns void
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_previous_audit_flag text;
BEGIN

    IF COALESCE(auth.role(), '') <> 'authenticated'
       OR auth.uid() IS NULL
    THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;


    v_previous_audit_flag :=
        current_setting(
            'app.audit_internal',
            true
        );


    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        summary,
        details
    )
    VALUES (
        'LOGIN',
        'เข้าสู่ระบบ',
        jsonb_build_object(
            'user_id', auth.uid()
        )
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );

END;
$function$;

create or replace function public.rename_fgcode (
  p_old_id             text,
  p_new_id             text,
  p_name               text,
  p_exp                text,
  p_default_paper_type text    default null::text,
  p_qty_per_a3         integer default null::integer
)
  returns integer
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_old public.fgcode%ROWTYPE;
    v_affected integer := 0;
    v_editor text;

    v_previous_rename_flag text;
    v_previous_audit_flag text;
BEGIN

    IF auth.role() <> 'authenticated' THEN
        RAISE EXCEPTION 'Authentication required';
    END IF;


    IF NOT public.is_user_manager() THEN
        RAISE EXCEPTION
            'Only Moderator or Assistant Moderator can change Product ID';
    END IF;


    p_old_id := btrim(p_old_id);
    p_new_id := btrim(p_new_id);
    p_name := btrim(p_name);
    p_exp := btrim(p_exp);


    IF p_old_id = ''
       OR p_new_id = '' THEN
        RAISE EXCEPTION 'Product ID cannot be empty';
    END IF;


    IF p_old_id = p_new_id THEN
        RAISE EXCEPTION
            'New Product ID must be different';
    END IF;


    IF p_name = '' THEN
        RAISE EXCEPTION
            'Product name cannot be empty';
    END IF;


    IF p_exp = ''
       OR p_exp !~ '^[0-9]+$'
       OR p_exp::integer <= 0 THEN
        RAISE EXCEPTION
            'Invalid product expiry';
    END IF;


    IF p_qty_per_a3 IS NOT NULL
       AND p_qty_per_a3 <= 0 THEN
        RAISE EXCEPTION
            'qty_per_a3 must be greater than 0';
    END IF;


    SELECT *
    INTO v_old
    FROM public.fgcode
    WHERE id = p_old_id
    FOR UPDATE;


    IF NOT FOUND THEN
        RAISE EXCEPTION
            'Product ID "%" not found',
            p_old_id;
    END IF;


    IF EXISTS (
        SELECT 1
        FROM public.fgcode
        WHERE id = p_new_id
    ) THEN
        RAISE EXCEPTION
            'Product ID "%" already exists',
            p_new_id;
    END IF;


    SELECT
        CASE
            WHEN u.employee_id IS NOT NULL
                 AND btrim(u.employee_id) <> ''
            THEN u.name || ' (' || u.employee_id || ')'
            ELSE u.name
        END
    INTO v_editor
    FROM public.users u
    WHERE u.id = auth.uid();


    v_editor := COALESCE(
        v_editor,
        'System'
    );


    -- ========================================================
    -- เปิด rename flag
    -- ป้องกัน trigger มอง INSERT+DELETE เป็น Create/Delete
    -- ========================================================

    v_previous_rename_flag :=
        current_setting(
            'app.fgcode_rename',
            true
        );


    PERFORM set_config(
        'app.fgcode_rename',
        'on',
        true
    );


    -- ========================================================
    -- สร้าง Product ID ใหม่
    -- ========================================================

    INSERT INTO public.fgcode (
        id,
        name,
        exp,
        created_at,
        default_paper_type,
        qty_per_a3
    )
    VALUES (
        p_new_id,
        p_name,
        p_exp,
        v_old.created_at,
        NULLIF(
            btrim(p_default_paper_type),
            ''
        ),
        p_qty_per_a3
    );


    -- ========================================================
    -- ย้าย Product ID ของ orders
    -- ========================================================

    WITH moved_orders AS (

        UPDATE public.orders o
        SET
            product_id = p_new_id,

            previous_product_name =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                         AND o.product_name
                             IS DISTINCT FROM p_name
                    THEN o.product_name
                    ELSE o.previous_product_name
                END,

            product_name =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                    THEN p_name
                    ELSE o.product_name
                END,

            product_exp =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                    THEN p_exp
                    ELSE o.product_exp
                END,

            expiry_date =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                    THEN (
                        o.production_date
                        + make_interval(
                            months => p_exp::integer
                        )
                    )::date
                    ELSE o.expiry_date
                END,

            updated_at =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                    THEN now()
                    ELSE o.updated_at
                END,

            updated_by =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                    THEN v_editor
                    ELSE o.updated_by
                END,

            edit_summary =
                CASE
                    WHEN o.is_verified = false
                         AND COALESCE(
                             o.is_cancelled,
                             false
                         ) = false
                    THEN format(
                        'รหัสสินค้าเปลี่ยน: %s ➡️ %s',
                        p_old_id,
                        p_new_id
                    )
                    ELSE o.edit_summary
                END

        WHERE o.product_id = p_old_id

        RETURNING o.id
    )

    SELECT count(*)
    INTO v_affected
    FROM moved_orders;


    -- ========================================================
    -- ลบ ID เดิม
    -- ========================================================

    DELETE FROM public.fgcode
    WHERE id = p_old_id;


    -- ========================================================
    -- Product-level trusted audit
    -- ========================================================

    v_previous_audit_flag :=
        current_setting(
            'app.audit_internal',
            true
        );


    PERFORM set_config(
        'app.audit_internal',
        'on',
        true
    );


    INSERT INTO public.audit_logs (
        action,
        details,
        changes
    )
    VALUES (
        'UPDATE_PRODUCT',

        jsonb_build_object(
            'old_id', p_old_id,
            'id', p_new_id,
            'name', p_name,
            'exp', p_exp,
            'default_paper_type',
                NULLIF(
                    btrim(p_default_paper_type),
                    ''
                ),
            'qty_per_a3', p_qty_per_a3,
            'affected_orders', v_affected
        ),

        jsonb_build_object(
            'id',
            jsonb_build_object(
                'old', p_old_id,
                'new', p_new_id
            )
        )
    );


    PERFORM set_config(
        'app.audit_internal',
        COALESCE(v_previous_audit_flag, ''),
        true
    );


    PERFORM set_config(
        'app.fgcode_rename',
        COALESCE(v_previous_rename_flag, ''),
        true
    );


    RETURN v_affected;
END;
$function$;

create or replace function public.set_order_creator()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_user_name text;
    v_department text;
BEGIN
    IF auth.role() = 'authenticated' THEN

        SELECT
            u.name,
            u.department
        INTO
            v_user_name,
            v_department
        FROM public.users u
        WHERE u.id = auth.uid();

        IF NOT FOUND THEN
            RAISE EXCEPTION 'User profile not found';
        END IF;

        -- ผู้สร้าง: เชื่อข้อมูลจาก DB เท่านั้น
        NEW.created_by_user_id := auth.uid();
        NEW.created_by := COALESCE(v_user_name, 'Unknown User');
        NEW.created_by_department :=
            COALESCE(v_department, 'ไม่ระบุหน่วยงาน');

        -- สถานะตอนสร้าง Order ต้องเริ่มจากค่าปลอดภัย
        NEW.is_verified := false;
        NEW.verified_by := NULL;
        NEW.verified_by_user_id := NULL;
        NEW.verified_at := NULL;

        NEW.is_printed := false;
        NEW.printed_by := NULL;
        NEW.printed_by_user_id := NULL;
        NEW.printed_at := NULL;

        NEW.is_cancelled := false;

        NEW.is_deleted := false;
        NEW.deleted_by := NULL;
        NEW.deleted_at := NULL;

        NEW.is_no_file := false;
        NEW.no_file_at := NULL;

        -- ข้อมูลผลผลิต ต้องไม่ได้มาจากตอนสร้าง Order
        NEW.paper_type := NULL;
        NEW.good_a3 := NULL;
        NEW.waste_a3 := NULL;
        NEW.waste_a3_remark := NULL;
        NEW.waste_qty := NULL;
        NEW.waste_qty_remark := NULL;
        NEW.reconciled_by := NULL;
        NEW.reconciled_at := NULL;
        NEW.qty_per_a3_used := NULL;

        NEW.updated_by := NULL;
        NEW.updated_by_user_id := NULL;
        NEW.updated_at := NULL;
    END IF;

    RETURN NEW;
END;
$function$;

create or replace function public.sync_orders_from_fgcode()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
DECLARE
    v_editor text;
    v_summary text;
    v_previous_internal_flag text;
BEGIN

    IF NEW.name IS NOT DISTINCT FROM OLD.name
       AND NEW.exp IS NOT DISTINCT FROM OLD.exp THEN
        RETURN NEW;
    END IF;


    SELECT
        CASE
            WHEN u.employee_id IS NOT NULL
                 AND btrim(u.employee_id) <> ''
            THEN u.name || ' (' || u.employee_id || ')'
            ELSE u.name
        END
    INTO v_editor
    FROM public.users u
    WHERE u.id = auth.uid();


    v_editor := COALESCE(v_editor, 'System');


    v_summary := concat_ws(
        ' | ',

        CASE
            WHEN NEW.name IS DISTINCT FROM OLD.name
            THEN format(
                'ชื่อสินค้าเปลี่ยน: %s ➡️ %s',
                OLD.name,
                NEW.name
            )
        END,

        CASE
            WHEN NEW.exp IS DISTINCT FROM OLD.exp
            THEN format(
                'อายุผลิตภัณฑ์เปลี่ยน: %s ➡️ %s เดือน',
                OLD.exp,
                NEW.exp
            )
        END
    );


    v_previous_internal_flag :=
        current_setting(
            'app.order_internal_write',
            true
        );


    -- bypass protection เฉพาะ DB sync นี้
    PERFORM set_config(
        'app.order_internal_write',
        'on',
        true
    );


    UPDATE public.orders o
    SET
        previous_product_name =
            CASE
                WHEN NEW.name IS DISTINCT FROM OLD.name
                THEN o.product_name
                ELSE o.previous_product_name
            END,

        product_name =
            CASE
                WHEN NEW.name IS DISTINCT FROM OLD.name
                THEN NEW.name
                ELSE o.product_name
            END,

        product_exp =
            CASE
                WHEN NEW.exp IS DISTINCT FROM OLD.exp
                THEN NEW.exp
                ELSE o.product_exp
            END,

        expiry_date =
            CASE
                WHEN NEW.exp IS DISTINCT FROM OLD.exp
                     AND btrim(NEW.exp) ~ '^[0-9]+$'
                THEN (
                    o.production_date
                    + make_interval(
                        months => btrim(NEW.exp)::integer
                    )
                )::date
                ELSE o.expiry_date
            END,

        updated_at = now(),
        updated_by = v_editor,
        edit_summary = v_summary

    WHERE o.product_id = NEW.id
      AND o.is_verified = false
      AND COALESCE(o.is_cancelled, false) = false;


    PERFORM set_config(
        'app.order_internal_write',
        COALESCE(v_previous_internal_flag, ''),
        true
    );


    RETURN NEW;
END;
$function$;

create or replace function public.sync_user_email()
  returns trigger
  language plpgsql
  security definer
  set search_path to ''
  AS $function$
BEGIN
  -- อัปเดต email ใน public.users เมื่อ auth.users email เปลี่ยน
  UPDATE public.users
  SET email = NEW.email
  WHERE id = NEW.id;

  RETURN NEW;
END;
$function$;

alter table "public"."orders"
  add constraint "orders_product_id_fkey" foreign key (product_id) references public.fgcode(id) on update cascade on delete restrict;

alter table "public"."paper_transactions"
  add constraint "paper_transactions_user_id_fkey" foreign key (user_id) references auth.users(id) on delete set null;

alter table "public"."users"
  add constraint "users_id_fkey" foreign key (id) references auth.users(id) on delete cascade;

alter table "public"."audit_logs"
  add constraint "audit_logs_user_id_fkey" foreign key (user_id) references public.users(id) on delete set null;

alter table "public"."orders"
  add constraint "orders_created_by_user_id_fkey" foreign key (created_by_user_id) references public.users(id) on delete set null;

alter table "public"."orders"
  add constraint "orders_printed_by_user_id_fkey" foreign key (printed_by_user_id) references public.users(id) on delete set null;

alter table "public"."orders"
  add constraint "orders_updated_by_user_id_fkey" foreign key (updated_by_user_id) references public.users(id) on delete set null;

alter table "public"."orders"
  add constraint "orders_verified_by_user_id_fkey" foreign key (verified_by_user_id) references public.users(id) on delete set null;

create index idx_audit_logs_created_at on public.audit_logs using btree (created_at desc);

create index idx_audit_logs_order_id on public.audit_logs using btree (order_id);

create index idx_orders_created_by_user_id on public.orders using btree (created_by_user_id);

create index idx_orders_printed_by_user_id on public.orders using btree (printed_by_user_id);

create index idx_orders_updated_by_user_id on public.orders using btree (updated_by_user_id);

create index idx_orders_verified_by_user_id on public.orders using btree (verified_by_user_id);

create index idx_stability_feeds_lot_number on public.stability_feeds using btree (lot_number);

create index idx_stability_feeds_not_deleted on public.stability_feeds using btree (is_deleted)
  where (is_deleted = false);

create index idx_stability_feeds_product_id on public.stability_feeds using btree (product_id);

create trigger on_auth_email_updated
  after update of email on auth.users
  for each row
  when (((old.email)::text IS DISTINCT FROM (new.email)::text))
  execute function public.sync_user_email();

create trigger trg_protect_audit_log_insert
  before insert on public.audit_logs
  for each row
  execute function public.protect_audit_log_insert();

create trigger trg_protect_audit_logs_immutable
  before delete or update on public.audit_logs
  for each row
  execute function public.protect_audit_logs_immutable();

create trigger trg_audit_fgcode_delete
  after delete on public.fgcode referencing OLD table as deleted_rows
  for each STATEMENT
  execute function public.audit_fgcode_delete();

create trigger trg_audit_fgcode_write
  after insert or update on public.fgcode
  for each row
  execute function public.audit_fgcode_write();

create trigger trg_protect_fgcode_fields
  before insert or update on public.fgcode
  for each row
  execute function public.protect_fgcode_fields();

create trigger trg_sync_orders_from_fgcode
  after update of name, exp on public.fgcode
  for each row
  execute function public.sync_orders_from_fgcode();

create trigger ensure_order_creator
  before insert on public.orders
  for each row
  execute function public.set_order_creator();

create trigger trg_audit_orders_changes
  after insert or delete or update on public.orders
  for each row
  execute function public.audit_orders_changes();

create trigger trg_block_orders_no_file_non_manager
  before update of is_no_file on public.orders
  for each row
  execute function public.block_orders_no_file_non_manager();

create trigger trg_protect_orders_update
  before update on public.orders
  for each row
  execute function public.protect_orders_update();

create trigger trg_audit_paper_transaction_delete
  after delete on public.paper_transactions referencing OLD table as deleted_rows
  for each STATEMENT
  execute function public.audit_paper_transaction_delete();

create trigger trg_audit_paper_transaction_insert
  after insert on public.paper_transactions referencing NEW table as inserted_rows
  for each STATEMENT
  execute function public.audit_paper_transaction_insert();

create trigger trg_protect_paper_transaction_fields
  before insert or update on public.paper_transactions
  for each row
  execute function public.protect_paper_transaction_fields();

create trigger trg_audit_stability_feed_changes
  after insert or update on public.stability_feeds
  for each row
  execute function public.audit_stability_feed_changes();

create trigger trg_protect_stability_feed_fields
  before insert or update on public.stability_feeds
  for each row
  execute function public.protect_stability_feed_fields();

create trigger trg_audit_users_write
  after insert or update on public.users
  for each row
  execute function public.audit_users_write();

create trigger trg_protect_user_signature_change
  before update of signature_url on public.users
  for each row
  execute function public.protect_user_signature_change();

create trigger trg_protect_users_security_fields
  before insert or update on public.users
  for each row
  execute function public.protect_users_security_fields();

create policy "audit_logs_select_authenticated" on "public"."audit_logs"
  for select
  to "authenticated"
  using (true);

create policy "fgcode_delete_manager" on "public"."fgcode"
  for delete
  to "authenticated"
  using (public.is_user_manager());

create policy "fgcode_insert_authenticated" on "public"."fgcode"
  for insert
  to "authenticated"
  with check (true);

create policy "fgcode_select_authenticated" on "public"."fgcode"
  for select
  to "authenticated"
  using (true);

create policy "fgcode_update_authenticated" on "public"."fgcode"
  for update
  to "authenticated"
  using (true)
  with check (true);

create policy "orders_delete_moderator" on "public"."orders"
  for delete
  to "authenticated"
  using ((public.is_user_moderator() AND (COALESCE(is_deleted, false) = true)));

create policy "orders_insert_authenticated" on "public"."orders"
  for insert
  to "authenticated"
  with check ((created_by_user_id = auth.uid()));

create policy "orders_select_authenticated" on "public"."orders"
  for select
  to "authenticated"
  using (true);

create policy "orders_update_authenticated" on "public"."orders"
  for update
  to "authenticated"
  using
    ((public.is_user_manager() or ((created_by_user_id = auth.uid()) AND (is_verified = false) AND (COALESCE(is_cancelled, false) = false) AND (COALESCE(is_deleted, false) =
    false))))
  with check ((public.is_user_manager() OR ((created_by_user_id = auth.uid()) AND (COALESCE(is_deleted, false) = false))));

create policy "Allow moderators only" on "public"."paper_reports"
  for all
  to "authenticated"
  using ((( select users.role
   from public.users
  where (users.id = auth.uid())) = ANY (ARRAY['moderator'::text, 'assistant_moderator'::text])));

create policy "paper_transactions_delete_manager" on "public"."paper_transactions"
  for delete
  to "authenticated"
  using (public.is_user_manager());

create policy "paper_transactions_insert_manager" on "public"."paper_transactions"
  for insert
  to "authenticated"
  with check (public.is_user_manager());

create policy "paper_transactions_select_authenticated" on "public"."paper_transactions"
  for select
  to "authenticated"
  using (true);

create policy "paper_transactions_update_manager" on "public"."paper_transactions"
  for update
  to "authenticated"
  using (public.is_user_manager())
  with check (public.is_user_manager());

create policy "stability_feeds_insert_allowed" on "public"."stability_feeds"
  for insert
  to "authenticated"
  with check (public.can_access_stability_feeds());

create policy "stability_feeds_select_allowed" on "public"."stability_feeds"
  for select
  to "authenticated"
  using (public.can_access_stability_feeds());

create policy "stability_feeds_update_allowed" on "public"."stability_feeds"
  for update
  to "authenticated"
  using (public.can_access_stability_feeds())
  with check (public.can_access_stability_feeds());

create policy "users_insert_manager" on "public"."users"
  for insert
  to "authenticated"
  with check (public.is_user_manager());

create policy "users_insert_own" on "public"."users"
  for insert
  to "authenticated"
  with check ((id = auth.uid()));

create policy "users_select_authenticated" on "public"."users"
  for select
  to "authenticated"
  using (true);

create policy "users_update_manager" on "public"."users"
  for update
  to "authenticated"
  using (public.is_user_manager())
  with check (public.is_user_manager());

create policy "users_update_own" on "public"."users"
  for update
  to "authenticated"
  using ((id = auth.uid()))
  with check ((id = auth.uid()));

alter publication "supabase_realtime" add table "public"."orders";

comment on extension "pg_cron" is 'Job scheduler for PostgreSQL';

revoke all on function "public"."audit_fgcode_delete"() from public;

grant execute on function "public"."audit_fgcode_delete"() to "postgres", "service_role";

revoke all on function "public"."audit_fgcode_write"() from public;

grant execute on function "public"."audit_fgcode_write"() to "postgres", "service_role";

revoke all on function "public"."audit_orders_changes"() from public;

grant execute on function "public"."audit_orders_changes"() to "postgres", "service_role";

revoke all on function "public"."audit_paper_transaction_delete"() from public;

grant execute on function "public"."audit_paper_transaction_delete"() to "postgres", "service_role";

revoke all on function "public"."audit_paper_transaction_insert"() from public;

grant execute on function "public"."audit_paper_transaction_insert"() to "postgres", "service_role";

revoke all on function "public"."audit_stability_feed_changes"() from public;

grant execute on function "public"."audit_stability_feed_changes"() to "postgres", "service_role";

revoke all on function "public"."audit_users_write"() from public;

grant execute on function "public"."audit_users_write"() to "postgres", "service_role";

revoke all on function "public"."block_orders_no_file_non_manager"() from public;

grant execute on function "public"."block_orders_no_file_non_manager"() to "postgres", "service_role";

revoke all on function "public"."can_access_stability_feeds"() from public;

grant execute on function "public"."can_access_stability_feeds"() to "authenticated", "postgres", "service_role";

revoke all on function "public"."is_user_manager"() from public;

grant execute on function "public"."is_user_manager"() to "authenticated", "postgres", "service_role";

revoke all on function "public"."is_user_moderator"() from public;

grant execute on function "public"."is_user_moderator"() to "authenticated", "postgres", "service_role";

revoke all on function "public"."protect_audit_log_insert"() from public;

grant execute on function "public"."protect_audit_log_insert"() to "postgres", "service_role";

revoke all on function "public"."protect_audit_logs_immutable"() from public;

grant execute on function "public"."protect_audit_logs_immutable"() to "postgres", "service_role";

revoke all on function "public"."protect_fgcode_fields"() from public;

grant execute on function "public"."protect_fgcode_fields"() to "postgres", "service_role";

revoke all on function "public"."protect_orders_update"() from public;

grant execute on function "public"."protect_orders_update"() to "postgres", "service_role";

revoke all on function "public"."protect_paper_transaction_fields"() from public;

grant execute on function "public"."protect_paper_transaction_fields"() to "postgres", "service_role";

revoke all on function "public"."protect_stability_feed_fields"() from public;

grant execute on function "public"."protect_stability_feed_fields"() to "postgres", "service_role";

revoke all on function "public"."protect_user_signature_change"() from public;

grant execute on function "public"."protect_user_signature_change"() to "postgres", "service_role";

revoke all on function "public"."protect_users_security_fields"() from public;

grant execute on function "public"."protect_users_security_fields"() to "postgres", "service_role";

revoke all on function "public"."record_login_audit"() from public;

grant execute on function "public"."record_login_audit"() to "authenticated", "postgres", "service_role";

revoke all on function "public"."rename_fgcode"(text, text, text, text, text, integer) from public;

grant execute on function "public"."rename_fgcode"(text, text, text, text, text, integer) to "authenticated", "postgres", "service_role";

revoke all on function "public"."set_order_creator"() from public;

grant execute on function "public"."set_order_creator"() to "postgres", "service_role";

revoke all on function "public"."sync_orders_from_fgcode"() from public;

grant execute on function "public"."sync_orders_from_fgcode"() to "postgres", "service_role";

revoke all on function "public"."sync_user_email"() from public;

grant execute on function "public"."sync_user_email"() to "postgres", "service_role";

revoke all on sequence "public"."stability_feeds_id_seq" from "authenticated";

grant usage on sequence "public"."stability_feeds_id_seq" to "authenticated";

grant select, update, usage on sequence "public"."stability_feeds_id_seq" to "postgres", "service_role";

revoke all on table "public"."audit_logs" from "authenticated";

grant select on table "public"."audit_logs" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."audit_logs" to "postgres", "service_role";

revoke all ("default_paper_type") on table "public"."fgcode" from "authenticated";

grant insert ("default_paper_type"), update ("default_paper_type") on table "public"."fgcode" to "authenticated";

revoke all ("exp") on table "public"."fgcode" from "authenticated";

grant insert ("exp"), update ("exp") on table "public"."fgcode" to "authenticated";

revoke all ("id") on table "public"."fgcode" from "authenticated";

grant insert ("id") on table "public"."fgcode" to "authenticated";

revoke all ("name") on table "public"."fgcode" from "authenticated";

grant insert ("name"), update ("name") on table "public"."fgcode" to "authenticated";

revoke all ("qty_per_a3") on table "public"."fgcode" from "authenticated";

grant insert ("qty_per_a3"), update ("qty_per_a3") on table "public"."fgcode" to "authenticated";

revoke all on table "public"."fgcode" from "authenticated";

grant delete, insert, select, update on table "public"."fgcode" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."fgcode" to "postgres", "service_role";

revoke all on table "public"."orders" from "authenticated";

grant delete, insert, select, update on table "public"."orders" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."orders" to "postgres", "service_role";

revoke all on table "public"."paper_reports" from "authenticated";

grant delete, insert, select, update on table "public"."paper_reports" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."paper_reports" to "postgres", "service_role";

revoke all on table "public"."paper_transactions" from "authenticated";

grant delete, insert, select, update on table "public"."paper_transactions" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."paper_transactions" to "postgres", "service_role";

revoke all on table "public"."stability_feeds" from "authenticated";

grant insert, select, update on table "public"."stability_feeds" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."stability_feeds" to "postgres", "service_role";

revoke all on table "public"."users" from "authenticated";

grant insert, select, update on table "public"."users" to "authenticated";

grant delete, insert, maintain, references, select, trigger, truncate, update on table "public"."users" to "postgres", "service_role";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "anon";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "authenticated";

alter default privileges for role "postgres" in schema "public" grant select, update, usage on sequences to "service_role";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "anon";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "authenticated";

alter default privileges for role "postgres" in schema "public" grant execute on FUNCTIONS to "service_role";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "anon";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "authenticated";

alter default privileges for role "postgres" in schema "public" grant delete, insert, maintain, references, select, trigger, truncate, update on tables to "service_role";

select cron.schedule_in_database('delete_old_audit_logs', '0 0 * * *', ' DELETE FROM public.audit_logs WHERE created_at < NOW() - INTERVAL ''7 days''; ', 'postgres', null, true);

